default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: mysql
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER']  %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
